### ISSUE TITLE
最新版

### ISSUE THREAD

**Issue by j0hn30n** [54only/AWD_Platform#1]
大佬，我下载的最新版，但是前端样式还是老版本的，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/19259150/68825065-d040df80-06d3-11ea-8539-8ab4a8c6cc1d.png)

**Comment by 54only** [comment]
不好意思，再更新一下吧



个人签名：***
办公电话：*****
电子邮件：1*********
 
发件人： Johnson
发送时间： 2019-11-14 11:42
收件人： 54only/AWD_Platform
抄送： Subscribed
主题： [54only/AWD_Platform] 最新版 (#1)
大佬，我下载的最新版，但是前端样式还是老版本的，请问是什么原因呢？
