### ISSUE TITLE
刚打完华东南赛区的国赛，感觉比赛平台和这个平台非常相似。

### ISSUE THREAD

**Issue by fjh1997** [54only/AWD_Platform#10]
平台方是赛宁网安，除了连接是用ssh密钥登录以外，其余界面几乎一模一样，请问作者是否有借鉴过他们的平台，感觉真心很好用。

**Comment by fjh1997** [comment]
![image](https://user-images.githubusercontent.com/25281816/125189027-d8666f00-e268-11eb-802d-ac50be50d299.png)

**Comment by 54only** [comment]
界面是参考过很多平台，内核是我自己写的。下次有机会，你可以导出前端，分析后端接口就知道区别了
