### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by j0hn30n** [54only/AWD_Platform#2]
大师傅，再次抱歉打扰你了，我自己写的dockerfile一直不对，能方便提供一下你之前的dockerfile吗？我的邮箱：john30n@163.com

**Comment by 54only** [comment]
docker 需要自己制作，Dockerfile 结合 subject 里面的脚本



个人签名：李武鹏
办公电话：13882540008
电子邮件：13882540008@qq.com 13882540008@139.com
 
From: Johnson
Date: 2019-11-19 11:01
To: 54only/AWD_Platform
CC: Subscribed
Subject: [54only/AWD_Platform] dockerfile (#2)
大师傅，再次抱歉打扰你了，我自己写的dockerfile一直不对，能方便提供一下你之前的dockerfile吗？我的邮箱：john30n@163.com

**Comment by Ashomes** [comment]
大师傅，能提供yunnam_simple的dockerfile做下参考么？自己写的一直启动不起来。我的邮箱：k1ea4c@qq.com

**Comment by j0hn30n** [comment]
> 大师傅，能提供yunnam_simple的dockerfile做下参考么？自己写的一直启动不起来。我的邮箱：[k1ea4c@qq.com](mailto:k1ea4c@qq.com)

我的只能做参考，我改了一下代码，我写的dockerfile不能用
