### ISSUE TITLE
是否有Python3的版本

### ISSUE THREAD

**Issue by Joynice** [54only/AWD_Platform#3]
是否有Python3的版本

**Comment by 54only** [comment]
可升级，带价回

 
发件人： Joynice
发送时间： 2019-12-09 10:13
收件人： 54only/AWD_Platform
抄送： Subscribed
主题： [54only/AWD_Platform] 是否有Python3的版本 (#3)
是否有Python3的版本

**Comment by Joynice** [comment]
我们也在研究，基本快实现了，以后可以谈论下
