### ISSUE TITLE
登录admin 用户无法跳转到后台页面

### ISSUE THREAD

**Issue by archimesan** [54only/AWD_Platform#7]
您好，普通用户登录正常，使用admin 用户登录也是到前台，无法跳转到后台页面，这是怎么回事，我使用 ubunto 系统
![微信图片_20200320002206](https://user-images.githubusercontent.com/21963628/77089506-de678980-6a40-11ea-9946-07a5a3c4082e.png)

**Comment by BMlovePanda** [comment]
看源码，只允许GET和POST方法。你页面跳转的时候是不是Method有问题？

**Comment by 54only** [comment]
试试改一下对应方法里面的 session.get('user_id') -> session.get('_user_id')
