### ISSUE TITLE
关于比赛时候队伍把容器内源码删库如何重新重置

### ISSUE THREAD

**Issue by N4ick** [54only/AWD_Platform#9]
师傅 您好 对于做比赛当中有些队伍操作不当导致源码删除 那么如何重置容器 从而正常比赛 不然一直check下去 qvq

**Comment by 54only** [comment]
python teamrestart.py containername

注意查询队伍的 containername ，不一定跟队伍号对应哟

**Comment by N4ick** [comment]
谢谢师傅 热心解答 非常感谢  不知道师傅有打算做一个3D攻击大屏的嘛 ？
